[package]
name = "interface"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_pancam = "0.13.0"
apis = {path="../../../apis", features = ["bevy"]}
simulation = { path = "../simulation"}
